default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: srcomaha_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: srcomaha_test
  host: localhost

production:
  <<: *default
  database: srcomaha_production
  host: localhost